name: "azure blob cache"
author: nurture-tech
description: "Azure blob storage actions cache with actions/cache@v2 passthrough"
inputs:
  account:
    description: Azure storage account name
    required: true
  container:
    description: Azure storage container name
    required: true
  use-azure-cli-auth:
    description: "Use previously run azure/login@v1 step to authenticate"
    required: false
  path:
    description: "A list of files, directories, and wildcard patterns to cache and restore"
    required: true
  key:
    description: "An explicit key for restoring and saving the cache"
    required: true
  use-fallback:
    description: "Use github actions/cache as fallback"
    required: false
    default: "true"
  # zip-option:
  #   description: zip options
  #   required: false
  #   default: -ryq
  # unzip-option:
  #   description: unzip options
  #   required: false
  #   default: -n
runs:
  using: node20
  main: "../dist/saveOnly/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
